language: python

python:
  - "3.7.3"
  - "3.6.4"

before_install:
  - mv travis-secrets.yaml secrets.yaml
  ### Remove stream component
  - sed -i 's/^stream:/#stream:/g' configuration.yaml

install:
  - pip3 install homeassistant
  - pip3 install colorlog

script:
  - hass -c . --script check_config --info all