###################################
##  cuckoo Clock simulation.
##  Plays the number of cuckoos per hour and 1 on the half hour.
##  Blatently stolen from Carlo Costanzo
##  https://github.com/CCOSTAN/Home-AssistantConfig/blob/300f4bad4f165c0a390f3f9c36c081455c684108/config/automation/System/CucKoo_Clock.yaml
###################################

- alias: Cuckoo Clock
  initial_state: 'on'
  trigger:
    - platform: time_pattern
      minutes: 00
      seconds: 20
    - platform: time_pattern
      minutes: 30
      seconds: 00

  condition:
    condition: and
    conditions:
      - condition: time
        after: '08:59:00'
        before: '22:01:00'
      - condition: template
        value_template: >
          {% if is_state('media_player.muse', 'playing') %}
            false
          {% else %}
            true
          {% endif %}

  action:
    - service: media_player.turn_on
      entity_id: media_player.muse

    - service: media_player.volume_set
      entity_id:
        - media_player.muse
      data:
        volume_level: 0.5

    - service: media_player.play_media
      data_template:
        entity_id:
          - media_player.muse
        media_content_id: >
          {% if now().strftime("%M")|int == 30 %}
          /local/sounds/cuckoo-clock-01.wav
          {% else %}
          /local/sounds/cuckoo-clock-{{now().strftime("%I")}}.wav
          {% endif %}
        media_content_type: audio/mp4