---

# Automations related to the Ring Doorbell

- alias: Ring Ding
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.ring_front_door_ding
    to: 'on'
  condition:
    condition: time
    after: '08:00:00'
    before: '21:00:00'
  action:
    - service: media_player.turn_on
      entity_id: media_player.muse
    - service: media_player.volume_set
      entity_id: media_player.muse
      data_template:
        volume_level: >
          {% if now().strftime("%H")|int < 12 and now().strftime("%H")|int > 6 %}
          0.5
          {% elif now().strftime("%H")|int > 12 and now().strftime("%H")|int < 20 %}
          0.8
          {% else %}
          0.5
          {% endif %}
    - service: tts.google_translate_say
      entity_id: media_player.muse
      data:
        message: We have a visitor at the front door
    - service: script.tweet_engine
      data_template:
        message: 
          tweet: >
            {{ [
              "Someone tickled my Ring Doorbell at {{ states.sensor.ring_front_door_last_ding.state }}",
              "Quick!!! Hide!!!!  Someone just pressed my Ring Doorbell!",
              "Someone just touched the magic button of my Ring Doorbell.  Oh yeeeeeeah",
              "Everyone welcome our new visitor.  They just pressed my Ring Doorbell"
            ] | random }}