---

# Automations related to severe weather conditions


# NOAA Alerts
- alias: Noaa Alert - Text
  initial_state: 'on'
  trigger:
    entity_id: sensor.noaa_alerts_txz205
    from: ‘0’
    platform: state
  action:
    - service: persistent_notification.create
      data_template:
        message: ‘{{ states.sensor.noaa_alerts_txz205.attributes.description }}’

    - service: notify.pushbullet
      data_template:
        message: '{{ states.sensor.noaa_alerts_txz205.attributes.headline }}'
      
- alias: Noaa Alert - TTS
  initial_state: 'on'
  trigger:
    entity_id: sensor.noaa_alerts_txz205
    from: ‘0’
    platform: state
  condition:
    condition: time
    after: '07:00:00'
    before: '23:00:00'  
  action:
    - service: media_player.turn_on
      entity_id: media_player.muse
    - service: media_player.volume_set
      entity_id: media_player.muse
      data_template:
        volume_level: >
          {% if now().strftime("%H")|int < 12 and now().strftime("%H")|int > 6 %}
          0.5
          {% elif now().strftime("%H")|int > 12 and now().strftime("%H")|int < 20 %}
          0.8
          {% else %}
          0.5
          {% endif %}
    - service: tts.google_translate_say
      entity_id: media_player.muse
      data_template:
        message: ‘Attention.  Weather Alert follows. {{ states.sensor.noaa_alerts_txz205.attributes.headline }}’

# Allergy Notifications