---

# Travis-CI package

sensor:
  - platform: travisci
    api_key: !secret travis_token
    # repository: atomicpapa/hassconfig
    branch: master
    scan_interval: 2400
    monitored_conditions:
      - state