---

# Travis-CI package

sensor:
  - platform: travisci
    api_key: !secret travis_ci_sensor_token
    # repository: atomicpapa/hassconfig
    branch: master
    monitored_conditions:
      - state