---

#############################################################
#                                                           #
# Custom Component Config to get Weather Alerts from NOAA   #
#                                                           #
# https://github.com/custom-components/weatheralerts        #
#                                                           #
#############################################################

sensor:
  - platform: weatheralerts
    sameid: '048029'