---
######  Automations that run at midnight every day  #######

- alias: 'Timed 0000'
  initial_state: 'on'
  trigger:
    platform: time
    at: '00:00:00'

  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.dude_meds

    - service: mqtt.publish
      data:
        topic: hass/state/mail
        payload: 'No'
        retain: 'true'